### PR TITLE
Make midstatec extension module installable. 

### PR DESCRIPTION
**Pull request by rishta**

### CODE REVIEW

**Comment by slush0** [comment]
Why did you change architecture from "all" to i386/amd64? I'm running proxy on ARM without any issue...

**Comment by rishta** [comment]
Because midstatec.so is binary. Arch can't be "all" then or lintian will
complain. You may add arm if it builds there, I didn't test it for all
arches.

2015-05-11 11:00 GMT+02:00 slush0 <notifications@github.com>:

**Comment by slush0** [comment]
midstatec module is optional, there's pure python implementation as well, so technically it is platform independent. But nevermind, thanks for contribution!

**Comment by derenma** [comment]
@JohnAckison Shut the actual fuck up.  Others get notifications you cunt.

**Comment by derenma** [comment]
@JohnAckison Reported and blocked.

**Pull request merged**
